import estate from '/public/assets/real_estate.jpg'
import gold from '/public/assets/gold.jpg'
import agri from '/public/assets/agriculture.jpg'
import btc from '/public/assets/bitcoin.jpg'

export const secData = [
  {
  title: 'Real Estate',
  desc: "Real estate investment encompasses the acquisition, possession, oversight, leasing, or divestiture of land and its structures to yield returns. A time-tested path to enduring prosperity, real estate can furnish consistent revenue via rentals or leases. Its comparatively stable nature tempers volatility, offering a reliable portfolio cornerstone. As demand swells, property value often ascends, yielding capital gains upon sale. Moreover, real estate's divergence from other assets often bolsters portfolio diversification.",
  img: estate,
  bg: 'none'
},

{
  title: 'Gold',
  desc: "Gold, revered for ages as a wealth reservoir and currency, offers multifaceted advantages to portfolios. Its pivotal role as an inflation buffer is paramount—while currency value diminishes, gold holds steady, preserving purchasing power. Further, gold's distinct non-correlation with stocks and bonds enhances diversification. A refuge in economic uncertainty, it extends stability and shelter to investors, solidifying its stature as a secure haven asset.",
  img: gold,
  bg: '#263238',
  reverse: true
},

{
  title: 'Agriculture',
  desc: "Agriculture encompasses land cultivation, animal husbandry, and the creation of sustenance, fibers, and goods. Embarking on agricultural investment reaps a sustainable revenue stream via crops, leases, or livestock. With escalating worldwide demands, agriculture promises enduring expansion potential. Its nonalignment with conventional assets augments portfolio diversification. Additionally, agriculture investments wield positive environmental and societal influence—fostering sustainable farming methods and enhancing global food security for communities.",
  img: agri,
  bg: 'none'
},

{
  title: 'Stocks & Crypto',
  desc: "Venturing into financial assets opens avenues for growth and diversification. Stocks entail trading shares of public companies for capital gains or dividends, offering prospects despite market volatility. Cryptocurrency trading, hinged on cryptographic security, introduces a novel digital investment avenue. Although it carries high-return potential, the volatile and risky nature of cryptocurrencies demands prudence. Armed with knowledge and strategy, investors can harness these assets' advantages while managing risks. Sound comprehension of both stock and crypto trading nuances is pivotal, enabling informed choices. Relying on a dependable broker or advisor, investors adeptly navigate markets, forging a diversified portfolio aligned with their goals.",
  img: btc,
  bg: '#263238',
  reverse: true
}
]


export const testimonies = [
  {
    name: 'Sophie M',
    message: "Octavia Antonya Cephas has made navigating the complex world of finance a breeze. Her extensive range of services reflects her expertise. Octavia's friendly demeanor and organized approach have made managing my investments effortless. For all things related to brokerage and financial planning, she's the one I trust.",
  },
  {
    name: 'Daniel R',
    message: "Octavia Antonya Cephas epitomizes excellence in brokerage services. Her unwavering dedication to ensuring customer satisfaction sets her apart. With a secure approach, authentic insights, and swift responsiveness, every interaction is seamless. If you're looking for a broker who delivers results, I wholeheartedly recommend Octavia Antonya Cephas!",
  },
  {
    name: 'Laura G',
    message: "I've had the privilege of working with Octavia Antonya Cephas for some time now, and her professionalism and knowledge continue to impress me. She provides thoughtful advice tailored to my financial goals and risk tolerance. Octavia's commitment to her clients' success is truly remarkable.",
  },
  {
    name: 'Michael B',
    message: "Octavia Antonya Cephas's financial expertise has been a game-changer for me. Her insights into market trends and her ability to explain complex concepts in simple terms have empowered me to make better financial decisions. Her services have exceeded my expectations in every way.",
  },
  {
    name: 'Sarah L',
    message: "Octavia Antonya Cephas's commitment to her clients is truly commendable. Her dedication to achieving financial goals is evident in every interaction. Her insights have helped me navigate volatile markets with confidence, and her friendly approach makes discussing finances a breeze.",
  },
  {
    name: 'Matthew H',
    message: "Working with Octavia Antonya Cephas has been enlightening. Her advice extends beyond mere financial matters; she's a holistic wealth advisor. Her personalized approach and genuine care for her clients' financial well-being are what set her apart. I'm grateful for her guidance.",
  },
  {
    name: 'Sophia T',
    message: "Octavia Antonya Cephas's expertise stands out in a crowded financial landscape. Her knowledge of investment opportunities and risk management is unparalleled. She's not only helped me make informed decisions but also educated me along the way. I highly recommend her services.",
  },
  {
    name: 'John P',
    message: "Octavia Antonya Cephas is a financial wizard. Her ability to foresee market trends and recommend timely actions is remarkable. I've achieved significant growth in my investments under her guidance. She's not just a financial advisor; she's a strategic partner in wealth-building.",
  },
  {
    name: 'Elizabeth W',
    message: "I've been a client of Octavia Antonya Cephas for years, and her dedication to my financial success has never wavered. Her well-rounded expertise covers everything from retirement planning to tax-efficient investing. She's an invaluable asset in securing my financial future.",
  },
  {
    name: 'Nathan T',
    message: "Octavia Antonya Cephas's commitment to ethical financial practices is inspiring. Her recommendations are always aligned with my values, and her transparency in explaining financial strategies is refreshing. With her guidance, I've been able to achieve my financial goals while staying socially responsible.",
  },
  {
    name: 'Olivia C',
    message: "Navigating the world of finance was overwhelming until I found Octavia Antonya Cephas. Her patient and clear explanations have empowered me to take control of my financial decisions. Her insights have proven invaluable, and her customer-focused approach makes her stand out.",
  },
  {
    name: 'Isaac J',
    message: "Octavia Antonya Cephas's dedication to continuous learning is evident in her up-to-date knowledge of financial trends. She's proactive in adapting strategies to changing market conditions, which has led to consistent returns on my investments. Her expertise is second to none.",
  },
  {
    name: 'Sophie K',
    message: "I'm impressed by Octavia Antonya Cephas's commitment to education. She doesn't just tell me what to do; she explains the reasoning behind her recommendations. This has empowered me to make informed decisions about my financial future. Her guidance is truly transformative.",
  },
  {
    name: 'Ella M',
    message: "Octavia Antonya Cephas's personalized approach sets her apart. She takes the time to understand my financial aspirations and tailors strategies accordingly. Her availability for discussions and quick responses make me feel valued as a client. I highly recommend her services.",
  },
  {
    name: 'Alexander S',
    message: "I've worked with several financial advisors, but Octavia Antonya Cephas is in a league of her own. Her insights are forward-thinking, and her commitment to helping clients succeed is unwavering. With her guidance, I've not only protected my wealth but also seen substantial growth.",
  },
  {
    name: 'Sophia R',
    message: "Octavia Antonya Cephas's guidance extends beyond traditional finance. Her understanding of the digital economy and emerging technologies has helped me invest in future-oriented sectors. Her holistic approach to wealth management is truly commendable.",
  },
  {
    name: 'Elijah M',
    message: "In the unpredictable world of finance, Octavia Antonya Cephas is my anchor. Her steady advice and analytical insights have guided me through turbulent times. Her dedication to her clients' financial well-being is unmatched. I'm grateful to have her as my advisor.",
  },
];






export const countries = [
  { name: 'Afghanistan', code: '+93' },
  { name: 'Albania', code: '+355' },
  { name: 'Algeria', code: '+213' },
  { name: 'Andorra', code: '+376' },
  { name: 'Angola', code: '+244' },
  { name: 'Antigua and Barbuda', code: '+1-268' },
  { name: 'Argentina', code: '+54' },
  { name: 'Armenia', code: '+374' },
  { name: 'Australia', code: '+61' },
  { name: 'Austria', code: '+43' },
  { name: 'Azerbaijan', code: '+994' },
  { name: 'Bahamas', code: '+1-242' },
  { name: 'Bahrain', code: '+973' },
  { name: 'Bangladesh', code: '+880' },
  { name: 'Barbados', code: '+1-246' },
  { name: 'Belarus', code: '+375' },
  { name: 'Belgium', code: '+32' },
  { name: 'Belize', code: '+501' },
  { name: 'Benin', code: '+229' },
  { name: 'Bhutan', code: '+975' },
  { name: 'Bolivia', code: '+591' },
  { name: 'Bosnia and Herzegovina', code: '+387' },
  { name: 'Botswana', code: '+267' },
  { name: 'Brazil', code: '+55' },
  { name: 'Brunei', code: '+673' },
  { name: 'Bulgaria', code: '+359' },
  { name: 'Burkina Faso', code: '+226' },
  { name: 'Burundi', code: '+257' },
  { name: 'Cabo Verde', code: '+238' },
  { name: 'Cambodia', code: '+855' },
  { name: 'Cameroon', code: '+237' },
  { name: 'Canada', code: '+1' },
  { name: 'Central African Republic', code: '+236' },
  { name: 'Chad', code: '+235' },
  { name: 'Chile', code: '+56' },
  { name: 'China', code: '+86' },
  { name: 'Colombia', code: '+57' },
  { name: 'Comoros', code: '+269' },
  { name: 'Congo', code: '+242' },
  { name: 'Costa Rica', code: '+506' },
  { name: 'Cote d\'Ivoire', code: '+225' },
  { name: 'Croatia', code: '+385' },
  { name: 'Cuba', code: '+53' },
  { name: 'Cyprus', code: '+357' },
  { name: 'Czech Republic', code: '+420' },
  { name: 'Democratic Republic of the Congo', code: '+243' },
  { name: 'Denmark', code: '+45' },
  { name: 'Djibouti', code: '+253' },
  { name: 'Dominica', code: '+1-767' },
  { name: 'Dominican Republic', code: '+1-809' },
  { name: 'East Timor', code: '+670' },
  { name: 'Ecuador', code: '+593' },
  { name: 'Egypt', code: '+20' },
  { name: 'El Salvador', code: '+503' },
  { name: 'Equatorial Guinea', code: '+240' },
  { name: 'Eritrea', code: '+291' },
  { name: 'Estonia', code: '+372' },
  { name: 'Eswatini', code: '+268' },
  { name: 'Ethiopia', code: '+251' },
  { name: 'Fiji', code: '+679' },
  { name: 'Finland', code: '+358' },
  { name: 'France', code: '+33' },
  { name: 'Gabon', code: '+241' },
  { name: 'Gambia', code: '+220' },
  { name: 'Georgia', code: '+995' },
  { name: 'Germany', code: '+49' },
  { name: 'Ghana', code: '+233' },
  { name: 'Greece', code: '+30' },
  { name: 'Grenada', code: '+1-473' },
  { name: 'Guatemala', code: '+502' },
  { name: 'Guinea', code: '+224' },
  { name: 'Guinea-Bissau', code: '+245' },
  { name: 'Guyana', code: '+592' },
  { name: 'Haiti', code: '+509' },
  { name: 'Honduras', code: '+504' },
  { name: 'Hungary', code: '+36' },
  { name: 'Iceland', code: '+354' },
  { name: 'India', code: '+91' },
  { name: 'Indonesia', code: '+62' },
  { name: 'Iran', code: '+98' },
  { name: 'Iraq', code: '+964' },
  { name: 'Ireland', code: '+353' },
  { name: 'Israel', code: '+972' },
  { name: 'Italy', code: '+39' },
  { name: 'Jamaica', code: '+1-876' },
  { name: 'Japan', code: '+81' },
  { name: 'Jordan', code: '+962' },
  { name: 'Kazakhstan', code: '+7' },
  { name: 'Kenya', code: '+254' },
  { name: 'Kiribati', code: '+686' },
  { name: 'North Korea', code: '+850' },
  { name: 'South Korea', code: '+82' },
  { name: 'Kosovo', code: '+383' },
  { name: 'Kuwait', code: '+965' },
  { name: 'Kyrgyzstan', code: '+996' },
  { name: 'Laos', code: '+856' },
  { name: 'Latvia', code: '+371' },
  { name: 'Lebanon', code: '+961' },
  { name: 'Lesotho', code: '+266' },
  { name: 'Liberia', code: '+231' },
  { name: 'Libya', code: '+218' },
  { name: 'Liechtenstein', code: '+423' },
  { name: 'Lithuania', code: '+370' },
  { name: 'Luxembourg', code: '+352' },
  { name: 'Madagascar', code: '+261' },
  { name: 'Malawi', code: '+265' },
  { name: 'Malaysia', code: '+60' },
  { name: 'Maldives', code: '+960' },
  { name: 'Mali', code: '+223' },
  { name: 'Malta', code: '+356' },
  { name: 'Marshall Islands', code: '+692' },
  { name: 'Mauritania', code: '+222' },
  { name: 'Mauritius', code: '+230' },
  { name: 'Mexico', code: '+52' },
  { name: 'Micronesia', code: '+691' },
  { name: 'Moldova', code: '+373' },
  { name: 'Monaco', code: '+377' },
  { name: 'Mongolia', code: '+976' },
  { name: 'Montenegro', code: '+382' },
  { name: 'Morocco', code: '+212' },
  { name: 'Mozambique', code: '+258' },
  { name: 'Myanmar', code: '+95' },
  { name: 'Namibia', code: '+264' },
  { name: 'Nauru', code: '+674' },
  { name: 'Nepal', code: '+977' },
  { name: 'Netherlands', code: '+31' },
  { name: 'New Zealand', code: '+64' },
  { name: 'Nicaragua', code: '+505' },
  { name: 'Niger', code: '+227' },
  { name: 'Nigeria', code: '+234' },
  { name: 'North Macedonia', code: '+389' },
  { name: 'Norway', code: '+47' },
  { name: 'Oman', code: '+968' },
  { name: 'Pakistan', code: '+92' },
  { name: 'Palau', code: '+680' },
  { name: 'Palestine', code: '+970' },
  { name: 'Panama', code: '+507' },
  { name: 'Papua New Guinea', code: '+675' },
  { name: 'Paraguay', code: '+595' },
  { name: 'Peru', code: '+51' },
  { name: 'Philippines', code: '+63' },
  { name: 'Poland', code: '+48' },
  { name: 'Portugal', code: '+351' },
  { name: 'Qatar', code: '+974' },
  { name: 'Romania', code: '+40' },
  { name: 'Russia', code: '+7' },
  { name: 'Rwanda', code: '+250' },
  { name: 'Saint Kitts and Nevis', code: '+1-869' },
  { name: 'Saint Lucia', code: '+1-758' },
  { name: 'Saint Vincent and the Grenadines', code: '+1-784' },
  { name: 'Samoa', code: '+685' },
  { name: 'San Marino', code: '+378' },
  { name: 'Sao Tome and Principe', code: '+239' },
  { name: 'Saudi Arabia', code: '+966' },
  { name: 'Senegal', code: '+221' },
  { name: 'Serbia', code: '+381' },
  { name: 'Seychelles', code: '+248' },
  { name: 'Sierra Leone', code: '+232' },
  { name: 'Singapore', code: '+65' },
  { name: 'Slovakia', code: '+421' },
  { name: 'Slovenia', code: '+386' },
  { name: 'Solomon Islands', code: '+677' },
  { name: 'Somalia', code: '+252' },
  { name: 'South Africa', code: '+27' },
  { name: 'South Sudan', code: '+211' },
  { name: 'Spain', code: '+34' },
  { name: 'Sri Lanka', code: '+94' },
  { name: 'Sudan', code: '+249' },
  { name: 'Suriname', code: '+597' },
  { name: 'Sweden', code: '+46' },
  { name: 'Switzerland', code: '+41' },
  { name: 'Syria', code: '+963' },
  { name: 'Taiwan', code: '+886' },
  { name: 'Tajikistan', code: '+992' },
  { name: 'Tanzania', code: '+255' },
  { name: 'Thailand', code: '+66' },
  { name: 'Togo', code: '+228' },
  { name: 'Tonga', code: '+676' },
  { name: 'Trinidad and Tobago', code: '+1-868' },
  { name: 'Tunisia', code: '+216' },
  { name: 'Turkey', code: '+90' },
  { name: 'Turkmenistan', code: '+993' },
  { name: 'Tuvalu', code: '+688' },
  { name: 'Uganda', code: '+256' },
  { name: 'Ukraine', code: '+380' },
  { name: 'United Arab Emirates', code: '+971' },
  { name: 'United Kingdom', code: '+44' },
  { name: 'United States', code: '+1' },
  { name: 'Uruguay', code: '+598' },
  { name: 'Uzbekistan', code: '+998' },
  { name: 'Vanuatu', code: '+678' },
  { name: 'Vatican City', code: '+379' },
  { name: 'Venezuela', code: '+58' },
  { name: 'Vietnam', code: '+84' },
  { name: 'Yemen', code: '+967' },
  { name: 'Zambia', code: '+260' },
  { name: 'Zimbabwe', code: '+263' }
];
